name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rrdtool librrd-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio
    
    - name: Check code formatting
      run: |
        pip install black
        black --check opn/src/opnsense/scripts/hilink
    
    - name: Run linting
      run: |
        pip install pylint
        find opn/src -name "*.py" -exec pylint {} \; || true
    
    - name: Type checking
      run: |
        pip install mypy
        mypy opn/src/opnsense/scripts/hilink --ignore-missing-imports || true
    
    - name: Run tests
      run: |
        cd opn
        python -m pytest tests/ -v --cov=src/opnsense/scripts/hilink --cov-report=xml --cov-report=term
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./opn/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Bandit Security Scan
      uses: gaurav-nelson/bandit-action@v1
      with:
        path: "opn/src"
    
    - name: Run Safety check
      run: |
        pip install safety
        safety check -r opn/requirements.txt || true

  integration:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rrdtool librrd-dev
        python -m pip install --upgrade pip
        pip install -r opn/requirements.txt
    
    - name: Test service startup
      run: |
        cd opn
        timeout 10 python src/opnsense/scripts/hilink/hilink_service.py --foreground --debug || true
    
    - name: Test configuration manager
      run: |
        cd opn
        python -c "from src.opnsense.scripts.hilink.lib.config_manager import ConfigManager; cm = ConfigManager(); cm.load(); print('Config loaded successfully')"
    
    - name: Test HiLink API module
      run: |
        cd opn
        python -c "from src.opnsense.scripts.hilink.lib.hilink_api import HiLinkModem; print('HiLink API imported successfully')"